### ISSUE TITLE
请问有没有考虑整个帮助菜单

### ISSUE THREAD

**Issue by moyuguguji** [KarisAya/nonebot_plugin_game_collection#13]
插件指令有点多,请问能不能做个帮助菜单或者适配下nonebot-plugin-PicMenu

**Comment by NathanSummer** [comment]
> 插件指令有点多,请问能不能做个帮助菜单或者适配下nonebot-plugin-PicMenu

可以把README.md里面的功能介绍截成图片寄放在Postimage（或者其他托管），然后把图片（或者图库）链接放在回复词系统里面，用“游戏功能”做触发词就相当于帮助菜单的功能了

**Comment by KarisAya** [comment]
适配了nonebot-plugin-PicMenu
