### ISSUE TITLE
想问一下佬为什么配置完sign_gold和security_gold后会报错

### ISSUE THREAD

**Issue by ghost** [KarisAya/nonebot_plugin_game_collection#14]
![211247645-21ed2b7b-ee65-4d98-a5f0-c09b7fc4bd2d](https://user-images.githubusercontent.com/122252361/211302211-a7f5c937-9e10-41b4-8eed-0973e9316df3.png)

**Comment by KarisAya** [comment]
因为用的是括号，应该用中括号。新文档已经改了
