### ISSUE TITLE
道具剩余时间无法刷新

### ISSUE THREAD

**Issue by NathanSummer** [KarisAya/nonebot_plugin_game_collection#15]
![image](https://user-images.githubusercontent.com/88868171/211970995-dda36d91-6432-4132-9eb5-33e0ceb7410b.png)
被标记处找不到相应定义，是不是少装了什么东西

**Comment by KarisAya** [comment]
更新了，一堆bug,正在改

**Comment by NathanSummer** [comment]
> 更新了，一堆bug,正在改

感谢！

**Comment by KarisAya** [comment]
> 

2.0已发布
