### ISSUE TITLE
冻结资产能不能解除

### ISSUE THREAD

**Issue by NathanSummer** [KarisAya/nonebot_plugin_game_collection#16]
请问取消冻结的指令是？

**Comment by KarisAya** [comment]
除了确认码以外的所有回复都会取消冻结

**Comment by NathanSummer** [comment]
> 除了确认码以外的所有回复都会取消冻结

也就是说已经清算的无法解除

**Comment by KarisAya** [comment]
发送我的道具应该会看到被冻结的资产

然后发送使用道具 被冻结的资产 数量 就会恢复了。

**Comment by NathanSummer** [comment]
> 发送我的道具应该会看到被冻结的资产
> 
> 然后发送使用道具 被冻结的资产 数量 就会恢复了。

哦哦也就是说想要回复资产要先抽到那个道具！

**Comment by KarisAya** [comment]
这个道具不能抽，只有在冻结的时候自动生成

**Comment by NathanSummer** [comment]
> 这个道具不能抽，只有在冻结的时候自动生成

啊这，那没有使用条件嘛？

**Comment by KarisAya** [comment]
目前版本bug太多，新版还未发布建议先用1.7.0

**Comment by NathanSummer** [comment]
> 目前版本bug太多，新版还未发布建议先用1.7.0

啊这，已经开始用了😭
