### ISSUE TITLE
使用道具时报错

### ISSUE THREAD

**Issue by NathanSummer** [KarisAya/nonebot_plugin_game_collection#17]
为什么在使用初级元素的时候global_data.json会报错，
其他的都没什么问题

**Comment by KarisAya** [comment]
如果不想报错就在data_source.py 1593行加上

global_props = russian_manager.get_global_data(user_id)["props"]

不过建议忽略掉，初级元素约等于空气，相关内容完全没做。

**Comment by NathanSummer** [comment]
> 如果不想报错就在data_source.py 1593行加上
> 
> global_props = russian_manager.get_global_data(user_id)["props"]
> 
> 不过建议忽略掉，初级元素约等于空气，相关内容完全没做。

（？）好的，感谢感谢！

**Comment by NathanSummer** [comment]
辣个测试金库又是怎么用的嘞？解冻前要手动改成被冻结的资产嘛😂

**Comment by KarisAya** [comment]
道具id打错了，冻结应该给的是被冻结的资产，结果给成了测试金库（

**Comment by KarisAya** [comment]
会改的

**Comment by NathanSummer** [comment]
> 会改的

没事这个我自己先改着，还有那个初级元素改完你说的之后好像还有错的
data_source.py的line1599：global_props["03101"] -= count
这个应该改成33101吧，不然报错说这个地方03101不对来着
改完之后再运行它报错说'GameManager' object has no attribute 'cards_data_file'
是在data_source.py的line1077，好像是跟什么炼金有关系，这边是没有写完嘛？
