### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by Xiao-yux** [KarisAya/nonebot_plugin_game_collection#18]
![image](https://user-images.githubusercontent.com/79674967/213441976-d9ce0ded-5a69-4e7b-94c1-c819aaefb9d1.png)
这个游戏群友在玩时机器人偶尔会发给我（私聊发的），群里不会发这个图片了，也就偶尔会

**Comment by KarisAya** [comment]
不是bug，机器人风控没发出来就会把结果私发给管理。
以前在测试扑克对战时候的功能，现在看来没什么用了，下次更新取消。
