### ISSUE TITLE
ubuntu发送我的资产命令，图片缺字体

### ISSUE THREAD

**Issue by nikissXI** [KarisAya/nonebot_plugin_game_collection#22]
![}0NAC87EKNB@HFC$JR8CJ9M](https://user-images.githubusercontent.com/31379266/219095181-2dd1c7bc-f7d1-49c4-ad4a-1962a22073dd.PNG)
![image](https://user-images.githubusercontent.com/31379266/219095314-37f930f6-ea8a-4646-9c2b-9a2aab2eb8ab.png)

**Comment by KarisAya** [comment]
你是用什么方式安装的

**Comment by nikissXI** [comment]
pip install

**Comment by LittleMio** [comment]
看样子是缺少了Simsun（宋体）
你可以到网上下一份或者到Windows的fonts文件夹拷贝一份宋体
然后拷贝字体到字体目录

### 更新字体缓存:

```shell
sudo apt-get install ttf-mscorefonts-installer fontconfig
sudo mkfontscale
sudo mkfontdir
sudo fc-cache -fsv
```

**Comment by nikissXI** [comment]
> 

https://blog.csdn.net/BIT_666/article/details/122365074
用这个方法解决了
