### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Pennsy1** [KarisAya/nonebot_plugin_game_collection#25]
05-13 21:08:51 [ERROR] nonebot | Failed to import "nonebot_plugin_game_collection"
Traceback (most recent call last):
  File "/home/lighthouse/QQ/bot.py", line 14, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/home/lighthouse/QQ/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/lighthouse/QQ/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/lighthouse/QQ/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugins
    return set(
  File "/home/lighthouse/QQ/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/home/lighthouse/QQ/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/lighthouse/QQ/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lighthouse/QQ/.venv/lib/python3.10/site-packages/nonebot_plugin_game_collection/__init__.py", line 33, in <module>
    from .Manager import data, company_index
  File "/home/lighthouse/QQ/.venv/lib/python3.10/site-packages/nonebot_plugin_game_collection/Manager.py", line 11, in <module>
    from .utils.chart import text_to_png, gini_coef, default_BG
  File "/home/lighthouse/QQ/.venv/lib/python3.10/site-packages/nonebot_plugin_game_collection/utils/chart.py", line 27, in <module>
    font_big = ImageFont.truetype(font = fontname, size = 60, encoding = "utf-8")
  File "/home/lighthouse/QQ/.venv/lib/python3.10/site-packages/PIL/ImageFont.py", line 996, in truetype
    return freetype(font)
  File "/home/lighthouse/QQ/.venv/lib/python3.10/site-packages/PIL/ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/lighthouse/QQ/.venv/lib/python3.10/site-packages/PIL/ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by KarisAya** [comment]
应该是字体的问题

**Comment by Kimaru-bili** [comment]
我也出现了 请问要怎么解决呢？(╥╯^╰╥)
![image](https://github.com/KarisAya/nonebot_plugin_game_collection/assets/40233772/56b917ed-0c60-40ba-aff4-fd299eddc895)

**Comment by KarisAya** [comment]
> 我也出现了 请问要怎么解决呢？(╥╯^╰╥) ![image](https://user-images.githubusercontent.com/40233772/261958563-56b917ed-0c60-40ba-aff4-fd299eddc895.png)

安装字体，然后再配置里面加上

game_fontname = “/字体文件路径”

**Comment by Kimaru-bili** [comment]
> > 我也出现了 请问要怎么解决呢？(╥╯^╰╥) ![image](https://user-images.githubusercontent.com/40233772/261958563-56b917ed-0c60-40ba-aff4-fd299eddc895.png)
> 
> 安装字体，然后再配置里面加上
> 
> game_fontname = “/字体文件路径”

好的 我试试

**Comment by Kimaru-bili** [comment]
解决了 感谢作者（麻烦了

**Comment by Kimaru-bili** [comment]
![image](https://github.com/KarisAya/nonebot_plugin_game_collection/assets/40233772/a18df9f3-60fe-4427-8c50-7fc26af98145)
出现新错误了（悲
但好像不影响使用（刚开始没注意

**Comment by KarisAya** [comment]
> ![image](https://user-images.githubusercontent.com/40233772/262033814-a18df9f3-60fe-4427-8c50-7fc26af98145.png) 出现新错误了（悲 但好像不影响使用（刚开始没注意

可以设置[备用字体列表](https://github.com/KarisAya/nonebot_plugin_game_collection/tree/master#%EF%B8%8F-%E9%85%8D%E7%BD%AE)，这里是默认值，如果全部安装好或者指定其他一些本机已安装的备用字体就没报错了

**Comment by KarisAya** [comment]
默认值有Microsoft YaHei但是报错里面没有说明你已经安装好了微软雅黑（

**Comment by Kimaru-bili** [comment]
![image](https://github.com/KarisAya/nonebot_plugin_game_collection/assets/40233772/05098c17-c059-4334-89a3-611288dadc70)
可是我是安装过的（emm

**Comment by Kimaru-bili** [comment]
> ![image](https://user-images.githubusercontent.com/40233772/262037267-05098c17-c059-4334-89a3-611288dadc70.png) 可是我是安装过的（emm

甚至还装了几个思源字体 也没识别到 怪（用的docker ubuntu镜像

**Comment by Kimaru-bili** [comment]
![image](https://github.com/KarisAya/nonebot_plugin_game_collection/assets/40233772/4757f1ff-5687-47b6-80d6-c1630a77b15c)
这个也弄了 刷新缓存

**Comment by Kimaru-bili** [comment]
放弃力 谷歌了各种安装字体的方法还有改mplfinance设置都试力 全都无效（悲
dejavu字体也不是不能用（开摆 不用作者费心搞了

**Comment by KarisAya** [comment]
> 放弃力 谷歌了各种安装字体的方法还有改mplfinance设置都试力 全都无效（悲 dejavu字体也不是不能用（开摆 不用作者费心搞了

import matplotlib.font_manager as fm
default_fallback_path = fm.findfont(fm.FontProperties())
寻找字体的代码来自 matplotlib.font_manager.FontProperties()
你可能需要检查如何让 matplotlib 找到你的字体

**Comment by Kimaru-bili** [comment]
> > 放弃力 谷歌了各种安装字体的方法还有改mplfinance设置都试力 全都无效（悲 dejavu字体也不是不能用（开摆 不用作者费心搞了
> 
> import matplotlib.font_manager as fm default_fallback_path = fm.findfont(fm.FontProperties()) 寻找字体的代码来自 matplotlib.font_manager.FontProperties() 你可能需要检查如何让 matplotlib 找到你的字体

嗯 我之前谷歌也是 修改默认字体配置 清除字体缓存 然后回到Bot目录nb run运行以后还是找不到(乐 等会我再看看是不是哪里漏了忘记弄了 再逝逝
![Screenshot_2023-08-24-00-01-43-208_com android chrome](https://github.com/KarisAya/nonebot_plugin_game_collection/assets/40233772/a1bd6c53-8601-4d99-bf6a-ccca67b306c7)

**Comment by KarisAya** [comment]
> 放弃力 谷歌了各种安装字体的方法还有改mplfinance设置都试力 全都无效（悲 dejavu字体也不是不能用（开摆 不用作者费心搞了

终端执行
python3
import matplotlib.font_manager as fm
print("\n".join(map(lambda x:x.name,fm.fontManager.ttflist)))

![image](https://github.com/KarisAya/nonebot_plugin_game_collection/assets/51886078/426671f5-f3af-4a7a-a8c5-649d8f0b136e)
检查一下fm.fontManager能加载出那些字体

**Comment by Kimaru-bili** [comment]
![image](https://github.com/KarisAya/nonebot_plugin_game_collection/assets/40233772/b43f10e6-6b96-4612-8296-0cb9a8c00194)

**Comment by Kimaru-bili** [comment]
> ![image](https://user-images.githubusercontent.com/40233772/262741025-b43f10e6-6b96-4612-8296-0cb9a8c00194.png)

加载出来了 但是依旧读不到 草

**Comment by Kimaru-bili** [comment]
> > ![image](https://user-images.githubusercontent.com/40233772/262741025-b43f10e6-6b96-4612-8296-0cb9a8c00194.png)
> 
> 加载出来了 但是依旧读不到 草

我直接填Microsoft YaHei试试

**Comment by KarisAya** [comment]
> > ![image](https://user-images.githubusercontent.com/40233772/262033814-a18df9f3-60fe-4427-8c50-7fc26af98145.png) 出现新错误了（悲 但好像不影响使用（刚开始没注意
> 
> 可以设置[备用字体列表](https://github.com/KarisAya/nonebot_plugin_game_collection/tree/master#%EF%B8%8F-%E9%85%8D%E7%BD%AE)，这里是默认值，如果全部安装好或者指定其他一些本机已安装的备用字体就没报错了

加载到了

**Comment by Kimaru-bili** [comment]
![image](https://github.com/KarisAya/nonebot_plugin_game_collection/assets/40233772/fa307842-4d63-4b71-a698-fd1adc16515a)

**Comment by KarisAya** [comment]
这里没报[“Microsoft YaHei”] not found

**Comment by Kimaru-bili** [comment]
> 这里没报[“Microsoft YaHei”] not found

![image](https://github.com/KarisAya/nonebot_plugin_game_collection/assets/40233772/365ff23d-8068-4900-ac8c-10517bdfbfab)
这么填不行

**Comment by KarisAya** [comment]
> > ![image](https://user-images.githubusercontent.com/40233772/262033814-a18df9f3-60fe-4427-8c50-7fc26af98145.png) 出现新错误了（悲 但好像不影响使用（刚开始没注意
> 
> 可以设置[备用字体列表](https://github.com/KarisAya/nonebot_plugin_game_collection/tree/master#%EF%B8%8F-%E9%85%8D%E7%BD%AE)，这里是默认值，如果全部安装好或者指定其他一些本机已安装的备用字体就没报错了

这个是加载备用字体列表的报错，你配置这个干嘛
你看看配置

**Comment by KarisAya** [comment]
> > 这里没报[“Microsoft YaHei”] not found
> 
> ![image](https://user-images.githubusercontent.com/40233772/262741823-365ff23d-8068-4900-ac8c-10517bdfbfab.png) 这么填不行

我说的是你把这个列表里面的字体全部安装好就不报错了

# 默认备用字体
game_fallback_fonts = [
    "Arial",
    "Tahoma",
    "Microsoft YaHei",
    "Segoe UI",
    "Segoe UI Emoji",
    "Segoe UI Symbol",
    "Helvetica Neue",
    "PingFang SC",
    "Hiragino Sans GB",
    "Source Han Sans SC",
    "Noto Sans SC",
    "Noto Sans CJK JP",
    "WenQuanYi Micro Hei",
    "Apple Color Emoji",
    "Noto Color Emoji",
    ]

不配置的话，这些字体全安装了

**Comment by Kimaru-bili** [comment]
> > > ![image](https://user-images.githubusercontent.com/40233772/262033814-a18df9f3-60fe-4427-8c50-7fc26af98145.png) 出现新错误了（悲 但好像不影响使用（刚开始没注意
> > 
> > 
> > 可以设置[备用字体列表](https://github.com/KarisAya/nonebot_plugin_game_collection/tree/master#%EF%B8%8F-%E9%85%8D%E7%BD%AE)，这里是默认值，如果全部安装好或者指定其他一些本机已安装的备用字体就没报错了
> 
> 这个是加载备用字体列表的报错，你配置这个干嘛 你看看配置

第一行是默认显示字体吧 剩下的是备用字体（我是想把默认字体改到微软雅黑 备用的不管emmm

**Comment by Kimaru-bili** [comment]
> > > 这里没报[“Microsoft YaHei”] not found
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/40233772/262741823-365ff23d-8068-4900-ac8c-10517bdfbfab.png) 这么填不行
> 
> 我说的是你把这个列表里面的字体全部安装好就不报错了
> 
> # 默认备用字体
> game_fallback_fonts = [ "Arial", "Tahoma", "Microsoft YaHei", "Segoe UI", "Segoe UI Emoji", "Segoe UI Symbol", "Helvetica Neue", "PingFang SC", "Hiragino Sans GB", "Source Han Sans SC", "Noto Sans SC", "Noto Sans CJK JP", "WenQuanYi Micro Hei", "Apple Color Emoji", "Noto Color Emoji", ]
> 
> 不配置的话，这些字体全安装了

我主要想改默认字体 不让他变成Dejavu sans 用绝对路径就找不到 直接打Microsoft YaHei 就can't open resource

**Comment by KarisAya** [comment]
> > > > 这里没报[“Microsoft YaHei”] not found
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/40233772/262741823-365ff23d-8068-4900-ac8c-10517bdfbfab.png) 这么填不行
> > 
> > 
> > 我说的是你把这个列表里面的字体全部安装好就不报错了
> > # 默认备用字体
> > game_fallback_fonts = [ "Arial", "Tahoma", "Microsoft YaHei", "Segoe UI", "Segoe UI Emoji", "Segoe UI Symbol", "Helvetica Neue", "PingFang SC", "Hiragino Sans GB", "Source Han Sans SC", "Noto Sans SC", "Noto Sans CJK JP", "WenQuanYi Micro Hei", "Apple Color Emoji", "Noto Color Emoji", ]
> > 不配置的话，这些字体全安装了
> 
> 我主要想改默认字体 不让他变成Dejavu sans 用绝对路径就找不到 直接打Microsoft YaHei 就can't open resource

默认字体本来就是msyh,用绝对路径怎么就找不到了？你用绝对路径报错了吗？Dejavu sans是备用字体默认指定的

**Comment by Kimaru-bili** [comment]
> > > > > 这里没报[“Microsoft YaHei”] not found
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/40233772/262741823-365ff23d-8068-4900-ac8c-10517bdfbfab.png) 这么填不行
> > > 
> > > 
> > > 我说的是你把这个列表里面的字体全部安装好就不报错了
> > > # 默认备用字体
> > > game_fallback_fonts = [ "Arial", "Tahoma", "Microsoft YaHei", "Segoe UI", "Segoe UI Emoji", "Segoe UI Symbol", "Helvetica Neue", "PingFang SC", "Hiragino Sans GB", "Source Han Sans SC", "Noto Sans SC", "Noto Sans CJK JP", "WenQuanYi Micro Hei", "Apple Color Emoji", "Noto Color Emoji", ]
> > > 不配置的话，这些字体全安装了
> > 
> > 
> > 我主要想改默认字体 不让他变成Dejavu sans 用绝对路径就找不到 直接打Microsoft YaHei 就can't open resource
> 
> 默认字体本来就是msyh,用绝对路径怎么就找不到了？你用绝对路径报错了吗？Dejavu sans是备用字体默认指定的

![image](https://github.com/KarisAya/nonebot_plugin_game_collection/assets/40233772/26fa977a-299c-44e2-9e43-621001ad0c99)
这一行我只要改默认字体就会跟着变 应该不是备用字体吧

**Comment by KarisAya** [comment]
> > > > > > 这里没报[“Microsoft YaHei”] not found
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/40233772/262741823-365ff23d-8068-4900-ac8c-10517bdfbfab.png) 这么填不行
> > > > 
> > > > 
> > > > 我说的是你把这个列表里面的字体全部安装好就不报错了
> > > > # 默认备用字体
> > > > game_fallback_fonts = [ "Arial", "Tahoma", "Microsoft YaHei", "Segoe UI", "Segoe UI Emoji", "Segoe UI Symbol", "Helvetica Neue", "PingFang SC", "Hiragino Sans GB", "Source Han Sans SC", "Noto Sans SC", "Noto Sans CJK JP", "WenQuanYi Micro Hei", "Apple Color Emoji", "Noto Color Emoji", ]
> > > > 不配置的话，这些字体全安装了
> > > 
> > > 
> > > 我主要想改默认字体 不让他变成Dejavu sans 用绝对路径就找不到 直接打Microsoft YaHei 就can't open resource
> > 
> > 
> > 默认字体本来就是msyh,用绝对路径怎么就找不到了？你用绝对路径报错了吗？Dejavu sans是备用字体默认指定的
> 
> ![image](https://user-images.githubusercontent.com/40233772/262745698-26fa977a-299c-44e2-9e43-621001ad0c99.png) 这一行我只要改默认字体就会跟着变 应该不是备用字体吧

你安装好插件之后没有看到字体是微软雅黑吗？我一开始就说你的 __报错里面没有报微软雅黑__ 说明你微软雅黑是安装好的，后来我还告诉你这是 __备用字体没有找到__

**Comment by Kimaru-bili** [comment]
行吧

**Comment by KarisAya** [comment]
> 行吧

第一行是判断使用字体列表时排除默认字体的cmap,为了优化查找默认显示字体不支持的字符时替换速度，因为默认字体同时给pil和plt配置字体所以这个说明plt用到的默认字体不是微软雅黑，你需要配置一个pil与plt都认识的字体名。
pil可以识别路径作为源，但是plt不可以。

**Comment by KarisAya** [comment]
对于微软雅黑，plt与pil都认识的字体名是"msyh"

**Comment by Kimaru-bili** [comment]
OK(我对py了解的也不多 现学现用 抱歉了）不用管就行吧
