### ISSUE TITLE
关于签到

### ISSUE THREAD

**Issue by NathanSummer** [KarisAya/nonebot_plugin_game_collection#26]
现在每天签到都说已经签到了，本来有的群是这样，现在全是这样了
大佬有没有办法解决一下呜呜呜

**Comment by KarisAya** [comment]
先升级到最新版，然后使用Newday指令手动刷新签到，Newday指令每日0点自动触发。
如果Newday报错了把报错发我看一下

**Comment by NathanSummer** [comment]
> 先升级到最新版，然后使用Newday指令手动刷新签到，Newday指令每日0点自动触发。 如果Newday报错了把报错发我看一下

提示数据一切正常，然后删了一大堆备份
是不是定时任务出问题了

**Comment by KarisAya** [comment]
定时插件添加了容差参数，现在可以用了。
