### ISSUE TITLE
能不能增加一个限时开放游戏的功能呢

### ISSUE THREAD

**Issue by qjksxy** [KarisAya/nonebot_plugin_game_collection#3]
由于玩游戏的人太多了，正常聊天被严重干扰，所以能不能增加一个功能，让只在某个时间段可以进行游戏，比如周四上午，或者每天7:00到8:00之类的。
感谢大大！

**Comment by KarisAya** [comment]
在插件上实现要改好多东西的说。
管理上的问题还是用其他方法阻断吧。

**Comment by qjksxy** [comment]
目前找到了一些解决办法：nonebot_plugin_manager插件可以方便的在群聊中启用/禁用某个插件。但是还没办法实现自动控制，不知道作者是否有进一步建议呢
