### ISSUE TITLE
图片没有字体怎么办

### ISSUE THREAD

**Issue by Xiao-yux** [KarisAya/nonebot_plugin_game_collection#4]
![image](https://user-images.githubusercontent.com/79674967/185828021-4f7bca2d-797f-4165-b8a5-6763e130a44c.png)
![image](https://user-images.githubusercontent.com/79674967/185828039-5e91ec32-2b6f-485d-9147-9822f937b890.png)

**Comment by KarisAya** [comment]
参考 [nonebot_plugin_imageutils](https://github.com/noneplugin/nonebot-plugin-imageutils) 的readme
在系统的字体包里升级更新相关的字体文件
显示内容为𝐿𝒰𝒞𝒦𝒴 ✤ 𝒞𝐿𝒪𝒱𝐸𝑅
也可以在data_source.py第1351行修改成你想显示的文本。
