### ISSUE TITLE
新功能

### ISSUE THREAD

**Issue by Xiao-yux** [KarisAya/nonebot_plugin_game_collection#5]
建议出个超管指令，可以改自己金币。
这样就不用自己去修改文件了

**Comment by KarisAya** [comment]
目前有两个超管指令
刷新每日签到和每日补贴：reset_sign
刷新市场指数：reset_market_index

不过为了排除超管特权上述指令是全体成员有效的

**Comment by KarisAya** [comment]
获取金币，获取道具
