### ISSUE TITLE
轮盘决斗是否考虑增加观众下注

### ISSUE THREAD

**Issue by Danwk2333** [KarisAya/nonebot_plugin_game_collection#8]
[https://github.com/Rs794613/PcrDuel](url)
`@sv.on_rex(r'^支持(1|2)号(\d+)(金币|币)$')
async def on_input_duel_score(bot, ev: CQEvent):
    try:
        if duel_judger.get_on_off_support_status(ev.group_id):
            gid = ev.group_id
            uid = ev.user_id

            match = ev['match']
            select_id = int(match.group(1))
            input_score = int(match.group(2))
            print(select_id, input_score)
            score_counter = ScoreCounter2()
            # 若下注该群下注字典不存在则创建
            if duel_judger.get_support(gid) == 0:
                duel_judger.set_support(gid)
            support = duel_judger.get_support(gid)
            # 检查是否重复下注
            if uid in support:
                msg = '您已经支持过了。'
                await bot.send(ev, msg, at_sender=True)
                return
            # 检查是否是决斗人员
            duellist = duel_judger.get_duelid(gid)
            if uid in duellist:
                msg = '决斗参与者不能支持。'
                await bot.send(ev, msg, at_sender=True)
                return`
参考该链接大佬能不能在轮盘决斗等双人游戏中加入个群友下注环节，增加群友参与度（滑稽

**Comment by KarisAya** [comment]
之前想做下注机制来着，但是群友赌起来的时候对局会进行的非常快，下注超影响对局进行。
后来想了几个下注机制都没有实现，因为总是平衡不了时机。
所以一直摆了
